name: identity

services:

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5001:8080"
    depends_on:
      - database

  database:
    image: mysql:5.7.38
    environment:
      MYSQL_ROOT_PASSWORD: "identity"
      MYSQL_USER: "identity"
      MYSQL_PASSWORD: "identity"
      MYSQL_DATABASE: "identity"
    ports:
      - "3306:3306"
